#!/usr/bin/python
#
# Refer to the XML-RPC Javadoc to see what calls are available:
# http://docs.atlassian.com/software/jira/docs/api/rpc-jira-plugin/latest/com/atlassian/jira/rpc/xmlrpc/XmlRpcService.html
 
import xmlrpclib
import sys
import ConfigParser
import commands
import re
import getopt
import os.path

# Gerrit command
gerrit_cmd = "ssh gerrit gerrit"

# Config file path
config_path = os.path.expanduser('~/.jirettconfig')

config = ConfigParser.RawConfigParser()
config.read(config_path)

user = config.get('jira', 'user')
password = config.get('jira', 'pass')
url = config.get('jira', 'url')

rpc = xmlrpclib.ServerProxy(url)
auth = rpc.jira1.login(user, password)

def showUsage():
    print '\nNormal hook usage: ' + sys.argv[0] + ' --action [new|merged|abandoned] --change <change id> --commit <git hash> --change-url <url to change>'
    print '\nTo automatically update projects list in config: ' + sys.argv[0] + ' update-projects'

def updateProjects():
    projects = rpc.jira1.getProjectsNoSchemes(auth)
    s = ''
    for p in projects:
        s += p['key'] + ','

    s = s.rstrip(',')
    config.set('jira', 'projects', s)

    with open(config_path, 'wb') as configfile:
        config.write(configfile)
        
    print '\nAdded "' + s + '" to ' + config_path + '\n'

def updateTicket(what, id, hash, url):
    status, out = commands.getstatusoutput(gerrit_cmd + ' query --format TEXT change:' + id + ' limit:1')
    if (status != 0):
        print 'Could not run gerrit query command.\n' + out
        exit()
    subject = re.search('subject:.*[^\n]', out).group();
    projects = config.get('jira', 'projects').split(',')

    for p in projects:
        match = re.search('subject:.*(' + p + '-[0-9]+).*', subject).groups()[0]
        if (len(match) > 0):
            break
    if (len(match) > 0):
        if what == 'new':
            message = 'New patchset uploaded: '
        elif what == 'merged':
            message = 'Change merged: '
        elif what == 'abandoned':
            message = 'Changset abandonded: '
        else:
            print 'Illegal argument, stopping: ' + what
            exit()
        message += url + '\n'
        message += 'ChangeId: ' + id + '\n'
        if (len(hash) > 0):
            message += 'Commit: ' + hash+ '\n'
        rpc.jira1.addComment(auth, match, message)
        exit()


def main():

    if (len(sys.argv) < 2):
        showUsage()
        exit()

    if (sys.argv[1] == 'update-projects'):
        updateProjects()
        exit()

    need = ['action=', 'change=', 'change-url=', 'commit=', 'project=', 'branch=', 'uploader=',
            'patchset=', 'abandoner=', 'reason=', 'submitter=']
    optlist, args = getopt.getopt(sys.argv[1:], '', need)
    id = url = hash = ''

    for o, a in optlist:
        if o == '--change': id = a
        elif o == '--change-url': url = a
        elif o == '--commit': hash = a
        elif o == '--action': what = a

    if (len(what) > 0 and len(id) > 0 and len(url) > 0):
        updateTicket(what, id, hash, url)
    else:
        showUsage()
        
if __name__ == '__main__':
    main()




 
